name: Deploy Draft Release on Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Current path
        run: pwd

      - name: Copy files via SSH on Server 1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER_1 }}
          username: ${{ secrets.USERNAME_SERVER_1}}
          password: ${{ secrets.PASSWORD_SERVER_1}}
          source: "*"
          target: /home/my-app/